language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install nbformat
install:
  - travis_retry python setup.py install
script:
  - travis_retry python setup.py test
