# What Python version is installed where:
# https://www.appveyor.com/docs/build-environment/#python

environment:
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - set TMPDIR=C:\Temp
  - set CRAMSHELL=bash
  - set NBSTRIPOUT_EXE=%PYTHON%\Scripts\nbstripout.exe
  - git config --global core.autocrlf true

install:
  - mkdir -p C:\Temp
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install pytest==5.4.3"
  - "%PYTHON%/Scripts/pip install nbformat"
  - "%PYTHON%/Scripts/pip install --upgrade setuptools"
  - python setup.py install

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - python setup.py test
